"""Markdown report and SVG badge — made to paste into a PR or README."""

from __future__ import annotations

from .scoring import HealthReport

_GRADE_EMOJI = {"A": "🟢", "B": "🟢", "C": "🟡", "D": "🟠", "F": "🔴"}
_BADGE_COLORS = {"A": "#4c1", "B": "#97ca00", "C": "#dfb317", "D": "#fe7d37", "F": "#e05d44"}


def render_markdown(target: str, health: HealthReport,
                    churn_ranking: list[tuple[str, int, float, float]] | None = None,
                    deltas: list | None = None) -> str:
    """GitHub-flavored markdown summary for PR comments."""
    icon = _GRADE_EMOJI.get(health.grade, "⚪")
    lines = [
        f"## {icon} Codi health report — `{target}`",
        "",
        f"**Score: {health.score}/100 (grade {health.grade})**",
        "",
        "| Metric | Value |",
        "|---|---|",
        f"| Files | {health.total_files} |",
        f"| Source lines | {health.total_sloc:,} |",
        f"| Functions | {health.total_functions} |",
        f"| Avg complexity | {health.avg_complexity:.2f} |",
        f"| Docstring coverage | {health.docstring_coverage:.0%} |",
        f"| Type-hint coverage | {health.annotation_coverage:.0%} |",
        f"| Avg cognitive complexity | {health.avg_cognitive:.1f} |",
        f"| Duplication | {health.duplication:.0%} |",
        f"| Dead functions | {len(health.dead_functions)} |",
        f"| Import cycles | {len(health.cycles)} |",
    ]
    if deltas:
        lines += ["", "### Changes vs baseline", "",
                  "| Metric | Before | After | |", "|---|---|---|---|"]
        for d in deltas:
            mark = "✅" if d.improved else "❌"
            lines.append(f"| {d.metric} | {d.before} | {d.after} | {mark} |")
    if health.hotspots:
        lines += ["", "### Top hotspots", "",
                  "| Function | Location | CC | Why | Advice |", "|---|---|---|---|---|"]
        for h in health.hotspots[:5]:
            lines.append(f"| `{h.function.qualname}` | {h.file}:{h.function.lineno} "
                         f"| {h.function.complexity} | {'; '.join(h.reasons)} "
                         f"| {h.advice} |")
    if churn_ranking:
        lines += ["", "### Churn risk (commits × complexity)", "",
                  "| File | Commits | Avg CC | Risk |", "|---|---|---|---|"]
        for path, commits, cx, risk in churn_ranking[:5]:
            lines.append(f"| {path} | {commits} | {cx:.1f} | {risk} |")
    if health.cycles:
        lines += ["", "### ⚠ Circular imports", ""]
        lines += [f"- `{' → '.join(c)}`" for c in health.cycles]
    lines += ["", "_Generated by [Codi](https://github.com/Ibnuawf/codi) — "
              "zero-dependency Python code-health analyzer._", ""]
    return "\n".join(lines)


def render_badge(health: HealthReport) -> str:
    """Shields-style SVG badge showing the health score and grade."""
    label = "codi health"
    value = f"{health.score:.0f}/100 · {health.grade}"
    color = _BADGE_COLORS.get(health.grade, "#9f9f9f")
    lw = 6 * len(label) + 14
    vw = 6 * len(value) + 14
    w = lw + vw
    return (
        f'<svg xmlns="http://www.w3.org/2000/svg" width="{w}" height="20" '
        f'role="img" aria-label="{label}: {value}">'
        f'<linearGradient id="s" x2="0" y2="100%">'
        f'<stop offset="0" stop-color="#bbb" stop-opacity=".1"/>'
        f'<stop offset="1" stop-opacity=".1"/></linearGradient>'
        f'<clipPath id="r"><rect width="{w}" height="20" rx="3" fill="#fff"/></clipPath>'
        f'<g clip-path="url(#r)">'
        f'<rect width="{lw}" height="20" fill="#555"/>'
        f'<rect x="{lw}" width="{vw}" height="20" fill="{color}"/>'
        f'<rect width="{w}" height="20" fill="url(#s)"/></g>'
        f'<g fill="#fff" text-anchor="middle" '
        f'font-family="Verdana,Geneva,DejaVu Sans,sans-serif" font-size="11">'
        f'<text x="{lw / 2:.0f}" y="14">{label}</text>'
        f'<text x="{lw + vw / 2:.0f}" y="14">{value}</text></g></svg>'
    )
